---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sampleapis.poneding.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sampleapis.poneding.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - sampleapis.poneding.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
